<?php  
define('CFG_HTML_EDITOR','datadata1');
define('CFG_BACKUP_DIR','data1');
define('CFG_ADMINEMAIL','data1');
define('CFG_WEBNAME','/Dede1');
define('CFG_INDEXNAME','EwQOa4337U1');
define('CFG_INDEXURL','主页1');
define('CFG_COOKIE_ENCODE','我的网站1');
define('CFG_CMSPATH','manage/');
 ?>